function S = OmniTrakFileRead_Check_Field_Name(S,varargin)

%
%OmniTrakFileRead_Check_Field_Name.m - Vulintus, Inc.
%
%   OMNITRAKFILEREAD_CHECK_FIELD_NAME checks to see if the specified field
%   already exist in the data structure being generated by OmniTrakFileRead 
%   and creates the fields if they don't already exist. It is a recursive
%   function that calls itself until it gets to the end of all the
%   fieldnames and branchaes specified by the user.
%   
%   UPDATE LOG:
%   01/28/2021 - Drew Sloan - Function first implemented.
%   03/15/2022 - Drew Sloan - Rewritten to be recursive to allow for a 
%       variable number of new fields and subfields to be added.
%
%Notes for future updates:
%   The setfield function can handle non-scalar inputs, so it can be used
%   to create multiple field branches at a time, like this:
%
%       new_fields = {'field1','field2',field3',...}
%       setfield(data,new_fields{:},[]);
%
%   However, the isfield function does not handle non-scalar inputs, so
%   it's impossible to check if the field exists before creating it. The
%   getfield function handles non-scalar inputs, but it throws an error
%   when given field names that don't yet exist.
%

if nargin == 1                                                              %If only one input, the data structure, was supplied...
    return                                                                  %Skip execution of the rest of the function.
end

fieldname = varargin{1};                                                    %Grab the first fieldname.
if ~iscell(fieldname)                                                       %If the field name isn't a cell.
    fieldname = {fieldname};                                                %Convert it to a cell array.
end
for i = 1:numel(fieldname)                                                  %Step through each specified field name.       
    if ~isfield(S,fieldname{i})                                             %If the structure doesn't yet have the specified field...
        if numel(varargin) > 1                                              %If this isn't the last branch...
            S(1).(fieldname{i}) = [];                                       %Create the field as an empty value.
        else                                                                %Otherwise, if this is the last branch...
            S(1).(fieldname{i}) = struct([]);                               %Create the field as an empty structure.
        end
    end
    if numel(varargin) > 1                                                  %If there's more subfields to add...
        S(1).(fieldname{i}) = ...
            OmniTrakFileRead_Check_Field_Name(S(1).(fieldname{i}),...
            varargin{2:end});                                               %Recursively call the function to add them.
    end
end